spring:
  rabbitmq:
    addresses: 172.31.119.63:5672
    username: admin
    password: admin@dev
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

