## springboot整合rabbitmq的基本配置
spring:
  rabbitmq:
    addresses: 192.168.18.128:5672
    username: guest
    password: guest
    virtual-host: /
## 消费端配置
    listener:
      simple:
        concurrency: 2 #消费者数量
        ## manual:手动 ack（确认）
        acknowledge-mode: manual
        max-concurrency: 3
        prefetch: 1 #多个监听队列，能者多劳，